# Generated by Django 4.2.13 on 2024-09-22 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='expected_from_adeyinka',
            new_name='expected_from_sarah',
        ),
    ]
