# Generated by Django 4.2.13 on 2024-11-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_delete_booking_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='apis/newsletters/'),
        ),
    ]
