# Generated by Django 4.2.13 on 2024-11-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_gospelbandapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gospelbandapplication',
            name='terms_accepted',
        ),
    ]
