# Generated by Django 4.2.13 on 2025-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_remove_gospelbandapplication_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gospelbandapplication',
            name='application_type',
            field=models.CharField(choices=[('musician', 'Musician'), ('non-musician', 'Non-Musician')], default='musician', max_length=20),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='available_for_meetings',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='band_experience_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='expectations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='experience_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='hours_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='prior_experience',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='ref_contact2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='ref_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='relevant_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='role_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='willing_to_travel',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='worked_with_band',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='christian',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='church',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='church_ministry',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='experience_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='formal_training',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='group_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='hear_about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='instruments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='live_performance',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='ministry_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='music_notation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='other_groups',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='ref_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='ref_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='ref_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='regular_commitment',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='special_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='training_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='vocal_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='weekly_rehearsals',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gospelbandapplication',
            name='why_join',
            field=models.TextField(blank=True, null=True),
        ),
    ]
