# Generated by Django 4.2.13 on 2024-09-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_contact_delete_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('org_phone', models.CharField(max_length=20)),
                ('org_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=255)),
                ('event_nature', models.CharField(max_length=255)),
                ('expected_from_adeyinka', models.JSONField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_address_line1', models.CharField(max_length=255)),
                ('event_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('event_city', models.CharField(max_length=100)),
                ('event_state', models.CharField(max_length=100)),
                ('event_postal_code', models.CharField(max_length=20)),
                ('event_country', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('agreement1', models.BooleanField()),
                ('agreement2', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
