# Generated by Django 4.2.13 on 2024-10-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_address_line1_booking_addressline1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('instruments', models.CharField(blank=True, max_length=255, null=True)),
                ('vocal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('formal_music_training', models.BooleanField(default=False)),
                ('training_details', models.TextField(blank=True, null=True)),
                ('other_music_group', models.BooleanField(default=False)),
                ('other_music_group_details', models.CharField(blank=True, max_length=255, null=True)),
                ('can_read_music', models.BooleanField(default=False)),
                ('live_performance_experience', models.BooleanField(default=False)),
                ('is_christian', models.BooleanField(default=False)),
                ('church', models.CharField(blank=True, max_length=100, null=True)),
                ('involved_in_ministry', models.BooleanField(default=False)),
                ('ministry_details', models.TextField(blank=True, null=True)),
                ('motivation_to_join', models.TextField()),
                ('available_for_rehearsals', models.BooleanField(default=True)),
                ('availability_details', models.CharField(blank=True, max_length=255, null=True)),
                ('commitment_to_attend', models.BooleanField(default=True)),
                ('how_heard_about_band', models.CharField(blank=True, max_length=255, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('reference_name', models.CharField(max_length=255)),
                ('reference_contact_number', models.CharField(max_length=20)),
                ('reference_relationship', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
