# Generated by Django 4.2.13 on 2024-10-07 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_membershipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
