# Generated by Django 4.2.13 on 2024-11-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_host', models.CharField(max_length=255)),
                ('host_pastor', models.CharField(max_length=255)),
                ('event_name', models.TextField()),
                ('scripture', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('other_ministers', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=20)),
                ('other_event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vokim_expectations', models.TextField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_duration', models.CharField(max_length=20)),
                ('custom_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('sound_equipment', models.CharField(max_length=3)),
                ('equipment_details', models.TextField(blank=True, null=True)),
                ('event_category', models.CharField(max_length=255)),
                ('song_requests', models.TextField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=255, null=True)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terms_accepted', models.BooleanField()),
            ],
        ),
    ]
