# Generated by Django 4.2.13 on 2024-11-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_contactussubmission_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GospelBandApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('instruments', models.CharField(blank=True, max_length=200)),
                ('vocal_range', models.CharField(blank=True, max_length=20)),
                ('experience_years', models.CharField(max_length=50)),
                ('formal_training', models.CharField(max_length=3)),
                ('training_details', models.TextField(blank=True)),
                ('other_groups', models.CharField(max_length=3)),
                ('group_details', models.TextField(blank=True)),
                ('music_notation', models.CharField(max_length=3)),
                ('live_performance', models.CharField(max_length=3)),
                ('christian', models.CharField(max_length=3)),
                ('church', models.CharField(max_length=100)),
                ('church_ministry', models.CharField(max_length=3)),
                ('ministry_details', models.TextField(blank=True)),
                ('why_join', models.TextField()),
                ('weekly_rehearsals', models.CharField(max_length=3)),
                ('availability', models.TextField(blank=True)),
                ('regular_commitment', models.CharField(max_length=3)),
                ('hear_about', models.CharField(max_length=100)),
                ('special_skills', models.TextField(blank=True)),
                ('ref_name', models.CharField(max_length=100)),
                ('ref_contact', models.CharField(max_length=20)),
                ('ref_relationship', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
