# Generated by Django 4.2.13 on 2024-11-24 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_gospelbandapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='gospelbandapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gospelbandapplication',
            name='terms_accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
